export { default as Navigation } from "./Navigation";
export { default as Footer } from "./Footer";
export { default as Home } from "./Home";
export { default as Browse } from "./Browse";
export { default as Contact } from "./Contact";
export { default as Filter } from "./Filter";
export { default as Filter2 } from "./Filter2";
export { default as Profile} from "./forum/Profile";
export { default as Forum } from "./forum/Forum";
export { default as Posts } from "./forum/Posts";
export { default as Post } from "./forum/Post";
export { default as Account } from "./Account";
export { default as Ewaste } from "./activity/Ewaste";
export { default as CreatePost } from "./forum/CreatePost";
export { default as Thread } from "./forum/Thread";